name: Daily YRFI Prediction

on:
  schedule:
    # Ejecutar todos los días a las 13:00 UTC (9:00 AM hora de Nueva York)
    - cron: '0 13 * * *'
  # También permitir ejecución manual
  workflow_dispatch:

# Configurar permisos para el GITHUB_TOKEN
permissions:
  contents: write  # Permite hacer push de cambios al repositorio
  pull-requests: write  # Permite crear y actualizar pull requests
  statuses: write  # Permite actualizar estados de commits

jobs:
  predict:
    name: Generate YRFI Predictions
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run data initialization
      run: python scripts/initialize_season_data.py
    
    - name: Generate predictions
      run: python scripts/generar_pronosticos_jornada.py
    
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Configurar el usuario de git
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        
        # Configurar el remote con el token de autenticación
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        
        # Forzar la adición de archivos ignorados
        git add -f predictions/
        
        # Verificar si hay cambios para hacer commit
        if git diff --staged --quiet; then
          echo "No hay cambios para hacer commit"
          exit 0
        fi
        
        # Hacer commit
        git commit -m "Auto: Actualizar predicciones YRFI $(date +'%Y-%m-%d')" || echo "No hay cambios para hacer commit"
        
        # Hacer push
        git push origin HEAD:${GITHUB_REF#refs/heads/}
